changeLogFile=migration/db-changelog.xml
url=jdbc:postgresql://127.0.0.1:5432/attendance_db
username=postgres
password=password
classpath=/home/buildpiper/attendance-api/liquibase_lib/postgresql-42.5.4.jar
driver=org.postgresql.Driver

